### ISSUE TITLE
retrieving customer wait time

### ISSUE THREAD

**Issue by wteoh** [yarivr/lp-labs-agent-sdk#3]
is there a way to retrieve the customer wait time and have the bot join the conversation after a specific wait time has expires?

1. customer sends a message at 1400hrs
2. if no agent response after 30 minutes, bot joins conversation, sends message "our agents are currently occupied, we will respond to your enquiry as soon"
3. transfer back to skill

**Comment by yarivr** [comment]
Possible work around: 
1) create a "skill less" bot 
2) at off hours , the "skill less" bot will login and perform the steps 2 (sends message "our agents are currently occupied, we will respond to your enquiry as soon"), 3 (transfer back to skill)

**Comment by asafh** [comment]
@wteoh You could also have a bot user with Agent Manager permissions that does exactly that - monitors all conversations and sets a timer whenever a visitor sends a message (cleared upon agent message), timery expiry would have the bot join that conversation and send the message and/or transfer skill.
