### ISSUE TITLE
how to transfer to skill from dialog.js

### ISSUE THREAD

**Issue by wteoh** [yarivr/lp-labs-agent-sdk#6]
hi, can you kindly share how to transfer the conversation from a bot to human within the dialog.js?

Thanks

**Comment by yarivr** [comment]
Here is an example code:
               if (response == 'talk to an agent') {
                    session.send("Transferring you to an expert agent right away...");
                    session.endDialog({
                        "action": "transferToSkill",
                        "val": TRANSFER_SKILL
                    });
                    return;
                }
